# Generated by Django 6.1.1 on 2026-09-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sessionsignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemproposal',
            name='counter_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='problemproposal',
            name='counter_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problemproposal',
            name='last_action_by',
            field=models.CharField(default='mentor', max_length=20),
        ),
        migrations.AddField(
            model_name='problemproposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='problemproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('negotiating', 'Negotiating'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
